# Numpy Broadcasting

In [1]:
import numpy as np
np.random.seed(0)

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.  
Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.   
Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python.  
If the dimensions are not compatible, you will get a ValueError

![broadcast](../media/np_multiply_broadcasting.png)

In the simplest example of broadcasting, the scalar ``b`` is stretched to become an array of with the same shape as ``a`` so the shapes are compatible for element-by-element multiplication.

In [2]:
a = np.array([1, 2])
b = 1.6

print(a * b)

[1.6 3.2]


In [3]:
print(a + 5)

[6 7]


In [4]:
M = np.ones(shape=(2, 2))

print(M)

[[1. 1.]
 [1. 1.]]


In [5]:
print(M + a)

[[2. 3.]
 [2. 3.]]


In [6]:
a = np.arange(start=0, stop=3)
b = np.arange(start=0, stop=3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [7]:
print(a + b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [8]:
M = np.ones(shape=(2, 3))
a = np.arange(start=0, stop=3, step=1)

print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [9]:
print(M + a)

[[1. 2. 3.]
 [1. 2. 3.]]


In [10]:
a = np.arange(start=0, stop=9, step=1).reshape((3, 3))
b = np.arange(start=0, stop=3, step=1)

In [11]:
print(a)
print(b)

print(a + b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


### Standardization

In [12]:
x = np.random.normal(
    loc=5.0,
    scale=2.0,
    size=(100_000, 2)
)

In [13]:
x_mean = np.mean(x, axis=0)

print(x_mean)

[5.0001525  5.01318739]


In [14]:
x_var = np.var(x, axis=0)

print(x_var)

[3.98573966 3.98244747]


In [15]:
x_centered = x - x_mean

In [16]:
new_mean = np.mean(x_centered, axis=0)

print(new_mean)
print(np.equal(new_mean, 0.0))
print(np.isclose(new_mean, 0.0))

[-4.44956250e-14 -3.04893977e-14]
[False False]
[ True  True]


In [17]:
x_standardized = x_centered / (np.sqrt(1e-6 + x_var))

In [18]:
new_var = np.var(x_standardized, axis=0)

print(new_var)
print(np.equal(new_var, 1.0))
print(np.isclose(new_var, 1.0))

[0.99999975 0.99999975]
[False False]
[ True  True]
