# Exercise

In [6]:
import numpy as np

## Exercise 1:

Create a 2d array (5x5) with 1 on the border and 0 inside

In [7]:
M = np.ones((5, 5), dtype=np.float32)
M[1:-1, 1:-1] = 0

print(M)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Exercise 2:

Create a matrix (8x8) and fill it with a checkerboard pattern

In [8]:
M = np.zeros((8, 8), dtype=np.uint8)

M[1::2,::2] = 1
print(M)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [9]:
M[::2,1::2] = 1
print(M)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Exercise 3:

How to find the closest value in an 1D array

In [10]:
M = np.arange(100)
v = 74.7

index = np.argmin(np.abs(M - v))

print(M[index])

75


## Exercise 4:

How to get the n largest values of an 1D array

In [11]:
M = np.random.randn(100)
n = 5

print (M[np.argsort(M)[-n:]])

[1.74579371 1.89302662 1.99299787 2.02074261 2.71612998]
