# Exercise

In [17]:
import numpy as np
np.random.seed(0)

In [18]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

# Exercise 1

- Create an array (M) with the size 5x5 by sampling from an uniform int distribution $M_{i,j} \in [-10, 10]$

In [19]:
M = np.random.randint(low=-10, high=11, size=(5, 5))

In [20]:
array_info(M)

ndim: 2
shape: (5, 5)
size: 25
dtype: int32
values:
[[  2   5 -10  -7  -7]
 [ -3  -1   9   8  -6]
 [ -4   2  -9  -4  -3]
 [  4   7  -5   3  -2]
 [ -1  10   9   6   9]]



# Exercise 2

- Create an array (N) with the size 5x5 by sampling from an uniform float distribution $M_{i,j} \in [-10, 10)$

In [21]:
N = np.random.uniform(low=-10, high=10, size=(5, 5))

In [22]:
array_info(N)

ndim: 2
shape: (5, 5)
size: 25
dtype: float64
values:
[[ 9.14310318 -7.19298439  7.40174517 -0.52783909  6.01821504]
 [ 0.40954959  3.5775906   4.41265309  1.64039584  0.74746459]
 [ 5.17231249 -7.88184786 -0.52799161 -6.27335313  4.73836354]
 [-5.66899291 -7.29563653 -3.51717984 -7.00650266 -5.55357223]
 [-2.27022038  8.05196951 -1.0010002   2.26126916  8.04697166]]



# Exercise 3

- Count the number of elements of the matrix M and N where the elements are less than 0

In [23]:
M_idxs = np.count_nonzero(M < 0)
N_idxs = np.count_nonzero(N < 0)

In [24]:
print(M_idxs)
print(N_idxs)

13
12


# Exercise 4

- Replace all values of the matrix M and N that are less than 0 by 0

In [25]:
M[M < 0] = 0
N[N < 0] = 0

In [26]:
array_info(M)
array_info(N)

ndim: 2
shape: (5, 5)
size: 25
dtype: int32
values:
[[ 2  5  0  0  0]
 [ 0  0  9  8  0]
 [ 0  2  0  0  0]
 [ 4  7  0  3  0]
 [ 0 10  9  6  9]]

ndim: 2
shape: (5, 5)
size: 25
dtype: float64
values:
[[9.14310318 0.         7.40174517 0.         6.01821504]
 [0.40954959 3.5775906  4.41265309 1.64039584 0.74746459]
 [5.17231249 0.         0.         0.         4.73836354]
 [0.         0.         0.         0.         0.        ]
 [0.         8.05196951 0.         2.26126916 8.04697166]]



# Exercise 5

- Stack the matrix M and N on the axis=0 to a new matrix O

In [27]:
O = np.concatenate([M, N], axis=0)

In [28]:
array_info(O)

ndim: 2
shape: (10, 5)
size: 50
dtype: float64
values:
[[ 2.          5.          0.          0.          0.        ]
 [ 0.          0.          9.          8.          0.        ]
 [ 0.          2.          0.          0.          0.        ]
 [ 4.          7.          0.          3.          0.        ]
 [ 0.         10.          9.          6.          9.        ]
 [ 9.14310318  0.          7.40174517  0.          6.01821504]
 [ 0.40954959  3.5775906   4.41265309  1.64039584  0.74746459]
 [ 5.17231249  0.          0.          0.          4.73836354]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          8.05196951  0.          2.26126916  8.04697166]]



# Exercise 6

- Multiply the matrix O by np.pi
- Compute the cos for each value of the matrix O

In [29]:
O *= np.pi

In [30]:
array_info(O)

ndim: 2
shape: (10, 5)
size: 50
dtype: float64
values:
[[ 6.28318531 15.70796327  0.          0.          0.        ]
 [ 0.          0.         28.27433388 25.13274123  0.        ]
 [ 0.          6.28318531  0.          0.          0.        ]
 [12.56637061 21.99114858  0.          9.42477796  0.        ]
 [ 0.         31.41592654 28.27433388 18.84955592 28.27433388]
 [28.72390578  0.         23.25326824  0.         18.90678016]
 [ 1.28663799 11.23933235 13.86275854  5.15345552  2.34822926]
 [16.24929891  0.          0.          0.         14.8860081 ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.         25.29600826  0.          7.10398657 25.28030706]]



In [31]:
O = np.cos(O)

In [32]:
array_info(O)

ndim: 2
shape: (10, 5)
size: 50
dtype: float64
values:
[[ 1.         -1.          1.          1.          1.        ]
 [ 1.          1.         -1.          1.          1.        ]
 [ 1.          1.          1.          1.          1.        ]
 [ 1.         -1.          1.         -1.          1.        ]
 [ 1.          1.         -1.          1.         -1.        ]
 [-0.90063323  1.         -0.30379811  1.          0.99836314]
 [ 0.28034964  0.24135129  0.27097752  0.42690418 -0.70145214]
 [-0.85702122  1.          1.          1.         -0.68079039]
 [ 1.          1.          1.          1.          1.        ]
 [ 1.          0.98670152  1.          0.68163515  0.98913191]]

